SELECT
  sv.SEQUENCE,
  sv.SCRN_VW_TYPE_CD,
  sv.NAME,
  sv.PAR_CATEGORY,
  enu.STRING_VALUE,
  rus.STRING_VALUE
FROM
  S_SCREEN s
  JOIN S_SCREEN_VIEW sv ON sv.SCREEN_ID = s.ROW_ID
  LEFT JOIN S_SCREEN_VIEW cat ON cat.SCREEN_ID = s.ROW_ID AND cat.NAME = sv.PAR_CATEGORY  AND cat.SCRN_VW_TYPE_CD LIKE '%Category'
  LEFT JOIN S_SYM_STR str ON str.NAME = sv.MENU_TEXT_REF
  LEFT JOIN S_SYM_STR_INTL rus ON rus.SYM_STR_ID = str.ROW_ID AND rus.LANG_CD = 'RUS'
  LEFT JOIN S_SYM_STR_INTL enu ON enu.SYM_STR_ID = str.ROW_ID AND enu.LANG_CD = 'ENU'
  
WHERE
  s.NAME = 'User Profile Screen'
  AND sv.INACTIVE_FLG = 'N'
--  AND sv.PAR_CATEGORY = 'Action List'
--  AND sv.SCRN_VW_TYPE_CD LIKE 'Deta%'
ORDER BY sv.SEQUENCE
