SELECT R.ROW_ID ID,
       A.NAME,
       R.RPT_UOM,
       TO_CHAR(R.RPT_INTERVAL, '9999') RPT_INT,
       R.RPT_TYPE,
       R.SCHED_START_DT,
       R.SERVER_NAME,
       RP.VALUE WF_NAME
  FROM SIEBEL.S_SRM_REQUEST   R,
       SIEBEL.S_SRM_ACTION    A,
       SIEBEL.S_SRM_REQ_PARAM RP,
       SIEBEL.S_SRM_ACT_PARAM AP
 WHERE R.REQ_TYPE_CD = 'RPT_PARENT'
   AND R.STATUS = 'ACTIVE'
   AND R.ACTION_ID = A.ROW_ID
   AND RP.REQ_ID = R.ROW_ID
   AND AP.NAME = 'Workflow Process Name'
   AND AP.ACTION_ID = A.ROW_ID
   AND RP.ACTPARAM_ID = AP.ROW_ID
   AND (A.NAME = 'WfProcBatchMgr' OR SUBSTR(A.NAME, 1, 9) = 'WfProcMgr')
--   AND RP.VALUE NOT LIKE '%Fill List Mgmt%'
 ORDER BY R.ROW_ID;
